services:
  home-assistant:
    image: homeassistant/home-assistant:2026.2.3
    container_name: home-assistant_2026_2_3
    restart: always
    ports:
      - "8123:8123"
      - "5683:5683/udp"
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - /data/home-assistant:/config
      - /etc/letsencrypt:/certs
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
