generated_by: export_entity_snapshot.py
areas:
  - area_id: "aquarien"
    name: "Aquarien"
    aliases: "[]"
  - area_id: "bad"
    name: "Bad"
    aliases: "[]"
  - area_id: "bad_stay_on"
    name: "Bad (Stay On)"
    aliases: "[]"
  - area_id: "buro"
    name: "Büro"
    aliases: "[]"
  - area_id: "essraum"
    name: "Esstisch"
    aliases: "[]"
  - area_id: "gang"
    name: "Gang"
    aliases: "[]"
  - area_id: "kinderschlafzimmer"
    name: "Kinderschlafzimmer"
    aliases: "[]"
  - area_id: "kuche"
    name: "Küche"
    aliases: "[]"
  - area_id: "wohnzimmer"
    name: "Sofa"
    aliases: "[]"
  - area_id: "sonos_roam"
    name: "Sonos Roam"
    aliases: "[]"
  - area_id: "tv"
    name: "TV"
    aliases: "[]"
  - area_id: "trolley"
    name: "Trolley"
    aliases: "[]"
  - area_id: "wc"
    name: "WC"
    aliases: "[]"
  - area_id: "wohnzimmer_2"
    name: "Wohnzimmer"
    aliases: "[]"
  - area_id: "joshua"
    name: "Zimmer Joshua"
    aliases: "[]"
  - area_id: "spielzimmer"
    name: "Zimmer Julian"
    aliases: "[]"
  - area_id: "julian"
    name: "Zimmer Julian"
    aliases: "[]"
  - area_id: "schlafzimmer"
    name: "Zimmer Stephan"
    aliases: "[]"
